# Important Note

**Utilize applications powered by large language models (LLMs) to search for the necessary code and content to answer all the questions in this assignment. Avoid using Google Search. Create a login ID or account with well-known large language models like Copilot, ChatGPT, Gemini, and Claud. These platforms will provide the resources you need to complete the tasks effectively.**

---




# Q1) Use Gemini or any LLM to come up with new business or product ideas for millennials in Bangalore. The ideas should be aimed at software professionals and need only a small amount of money to start. Describe the prompts you used and share 3-5 of the most interesting ideas it came up with.

In [5]:
!pip install langchain
!pip install OpenAI
!pip install langchain_openai
!pip install langchain_community


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.5/88.5 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.8/505.8 kB 14.0 MB/s eta 0:00:00
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 1.2.19
    Uninstalling langchain-core-1.2.19:
      Successfully uninstalled langchain-core-1.2.19


In [11]:
import os
from google.colab import userdata
os.environ["OPENAI_API_KEY"]= userdata.get("OpenAI_API_key")

from openai import OpenAI
llm = OpenAI()


In [20]:
input= "ome up with new business or product ideas for millennials in Bangalore. The ideas should be aimed at software professionals and need only a small amount of money to start. Describe the prompts you used and share 3-5 of the most interesting ideas it came up with."
result = llm.responses.create(model="gpt-4.1-mini",
    input= input)
print(result.output_text)


Absolutely! Here’s how I approached generating business or product ideas tailored for software professionals who are millennials in Bangalore, with a minimal startup budget:

### Prompt Used:
"Generate innovative, low-investment business or product ideas targeted at millennial software professionals in Bangalore focusing on their lifestyle, work needs, and local environment."

---

### Top 5 Interesting Ideas:

1. **Remote Work Fitness and Ergonomics Kits**
   - **Concept:** Curated affordable kits containing ergonomic desk accessories (like a portable laptop stand, wrist rests) plus simple fitness tools (resistance bands, posture correction guides) tailored to home-office setups.
   - **Why It Fits:** Many software professionals work from home and face posture or fitness issues. This startup would resonate with their health-conscious mindset but limited budgets for expensive setups.
   - **Starting Small:** Source products from wholesale local vendors and assemble personalized kits on

In [21]:
from langchain_openai import OpenAI
llm = OpenAI(temperature=0.9, max_tokens=256)


input= "come up with new business or product ideas for millennials in Bangalore. The ideas should be aimed at software professionals and need only a small amount of money to start. Describe the prompts you used and share 3-5 of the most interesting ideas it came up with."

resut= llm.invoke(input)
print(resut)




Prompts used:
1. What are the current challenges faced by millennials in Bangalore?
2. How can technology help solve these challenges?
3. What are the unique skills and interests of software professionals in Bangalore?

1. Virtual Fitness Training App: With the busy lifestyle of software professionals, it can be a challenge for them to find time for physical fitness. A virtual fitness training app that offers personalized workout plans, live virtual classes, and nutrition advice can cater to the needs of this demographic. This business idea only requires a small investment in developing the app and hiring fitness trainers.

2. Eco-Friendly Food Delivery Service: Bangalore is known for its traffic and pollution, and millennials are increasingly becoming conscious of their impact on the environment. A food delivery service that uses eco-friendly packaging and delivers meals using electric bikes or rickshaws can attract this eco-conscious demographic. The initial investment would go tow

In [33]:
!pip install langchain_google_genai
from langchain_google_genai import ChatGoogleGenerativeAI



In [35]:
os.environ["GOOGLE_API_KEY"] = userdata.get("Gemini_API_Key")
llm  = ChatGoogleGenerativeAI(model="gemini-1.0-pro") # Changed model name to gemini-1.0-pro
input= "come up with new business or product ideas for millennials in Bangalore. The ideas should be aimed at software professionals and need only a small amount of money to start. Describe the prompts you used and share 3-5 of the most interesting ideas it came up with."

resut= llm.invoke(input)
print(resut)

ChatGoogleGenerativeAIError: Error calling model 'gemini-pro' (NOT_FOUND): 404 NOT_FOUND. {'error': {'code': 404, 'message': 'models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.', 'status': 'NOT_FOUND'}}

# Q2) Use Claude or any LLM to make 5 multiple-choice questions on pandas data handling and 5 on numpy. Try generating the questions several times and choose the best ones. Review the questions to ensure they are good and correct.

In [36]:
!pip install langchain_openai

from langchain_openai import OpenAI
llm = OpenAI(temperature= 0.8, max_tokens=256)

result = llm.invoke("make 5 multiple-choice questions on pandas data handling and 5 on numpy. Try generating the questions several times and choose the best ones. Review the questions to ensure they are good and correct")

print (result)




Pandas Data Handling:

1) Which of the following is NOT a valid data structure in pandas?
A) Series
B) Dataframe
C) Array
D) Panel

2) In order to read a CSV file into a pandas dataframe, which method should you use?
A) read_csv()
B) load_csv()
C) import_csv()
D) open_csv()

3) How would you select a specific column in a pandas dataframe?
A) df.select_column()
B) df.get_column()
C) df.loc['column_name']
D) df['column_name']

4) What is the purpose of the dropna() method in pandas?
A) To drop a specific row in a dataframe
B) To drop a specific column in a dataframe
C) To drop all rows with missing values
D) To drop all columns with missing values

5) Which of the following is the correct way to rename a column in a pandas dataframe?
A) df.rename_column('old_name', 'new_name')
B) df.rename('old_name', 'new_name', axis=1)
C) df.rename('new_name', 'old_name', columns=True)
D) df.rename(columns={'old_name':'new_name'})

Numpy:
1


# Q3) Building and Validating the model

In [38]:
!pip install scikit-learn

In [50]:
from sklearn.linear_model import LogisticRegression
!wget https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Credit%20Risk%20Data_balanced/Credit_risk_data_bal_v2.csv

--2026-03-24 02:15:57--  https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Credit%20Risk%20Data_balanced/Credit_risk_data_bal_v2.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 582478 (569K) [text/plain]
Saving to: ‘Credit_risk_data_bal_v2.csv’

Credit_risk_data_ba 100%[===================>] 568.83K  --.-KB/s    in 0.05s   

2026-03-24 02:15:57 (11.9 MB/s) - ‘Credit_risk_data_bal_v2.csv’ saved [582478/582478]



In [51]:
import pandas as pd
df= pd.read_csv("Credit_risk_data_bal_v2.csv")
df.head()

,SeriousDlqin2yrs,NumberOfTime30_59DaysPastDue1,util,age1,DebtRatio1,MonthlyIncome1,num_loans,depend
0,0,0,0.004731,76,0.173178,7396,1,1
1,0,0,0.003981,76,0.001148,4355,0,1
2,0,0,0.085806,76,0.034728,3800,0,1
3,0,0,0.024060,76,0.274502,1500,2,1
4,0,0,0.033871,76,0.158899,6500,1,1


## Q3.1) Write code to import data from the below location

https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Credit%20Risk%20Data_balanced/Credit_risk_data_bal_v2.csv

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['SeriousDlqin2yrs']), df['SeriousDlqin2yrs'], test_size=0.2, random_state=42 )



## Q3.2)  Write code for Splitting the data into Train Test

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['SeriousDlqin2yrs']), df['SeriousDlqin2yrs'], test_size=0.2, random_state=42 )



## Q3.3) Write code to build the model. Use 'SeriousDlqin2yrs' as target  variable and rest all as predictor variables. Print the beta co-efficients

In [60]:
####Model training

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [57]:
model.coef_

array([[ 8.38153646e-01,  1.91588791e+00, -4.04702668e-03,
         2.79506405e-01, -2.15651179e-05, -1.31706582e-01,
        -8.92217313e-01]])

In [58]:
model.intercept_

array([0.44679451])

## Q3.4)Perform Model Validation and Cross Validation on train and test data. Print the confusion matrix and accuracies

In [62]:
## Model validation
# get the prediction of both data

y_train_pred= model.predict(X_train)
y_test_pred=  model.predict(X_test)


#confusion matrix
from sklearn.metrics import confusion_matrix
cm_training= confusion_matrix(y_train,y_train_pred )
cm_testing = confusion_matrix(y_test,y_test_pred)

print("Train Confusion Matrix:\n", cm_training)
print("\nTest Confusion Matrix:\n", cm_testing)





Train Confusion Matrix:
 [[6581  883]
 [1570 2821]]

Test Confusion Matrix:
 [[1654  222]
 [ 404  684]]


In [63]:
from sklearn.metrics import accuracy_score

## accuracy
trianing_accuracy = accuracy_score(y_train,y_train_pred)
Tetsing_accuracy = accuracy_score(y_test,y_test_pred)

print("Train Accuracy:", trianing_accuracy)
print("Test Accuracy:", Tetsing_accuracy)

Train Accuracy: 0.7930830873049346
Test Accuracy: 0.7887989203778677


In [64]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    model,
    df.drop(columns=['SeriousDlqin2yrs']),
    df['SeriousDlqin2yrs'],
    cv=5,              # 5-fold CV
    scoring="accuracy"
)

print("Cross-validation scores:", cv_scores)
print("Mean CV accuracy:", cv_scores.mean())

Cross-validation scores: [0.68792173 0.81578947 0.77462888 0.77834008 0.6317921 ]
Mean CV accuracy: 0.7376944529084074


# Q4) Download the image from the below location and answer the below questions
https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Inoices/Invoice_3.png



# Q4.1) Upload the image on to Claude website, get the summary of the invoice images

## Q4.2) Ask questions to extract information like address mentioned in the invoice, invoice total amount, email address and bank account number.

# Q5) What are the five key elements to consider when interacting with an LLM using prompts? Describe each element in two lines and include simple examples.

In [ ]:
1>> ROLE play
2>> Few shots example
3>> Domain aware
4>> output display format
5>> iterations

# Q6) Provide a list of the LLMs released by the world's top 10 companies.


In [ ]:
# 1) OpenAI- ChatGPT
# 2)  d

# Q7) What data science and data analytics tasks can LLM models currently manage? Describe how they handle these tasks in 10 points.

In [65]:
result = llm.invoke("What data science and data analytics tasks can LLM models currently manage? Describe how they handle these tasks in 10 points.")

In [66]:
print(result)



1. Data cleaning and preprocessing: LLM models are capable of handling data cleaning and preprocessing tasks, which involve identifying and correcting missing values, outliers, and errors in the data to prepare it for analysis.

2. Feature selection and extraction: LLM models can automatically identify the most relevant features from a large dataset and extract meaningful information from them, reducing the noise and complexity of the data.

3. Prediction and classification: LLM models are commonly used for predictive modeling and classification tasks, such as predicting future trends or identifying patterns in data to classify it into different categories.

4. Anomaly detection: LLM models can detect anomalies or unusual patterns in data that deviate from the expected or normal behavior, which can be useful for fraud detection, fault diagnosis, and other applications.

5. Natural Language Processing (NLP): LLM models have been successfully applied to NLP tasks, such as sentiment ana